micronaut:
  application:
    name: pixRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
      plaintext: true
      transport-security: true
      max-retry-attempts: 10


jackson:
  serialization:
    writeDatesAsTimestamps: false